### ISSUE TITLE
the .obj result of test examples are weird

### ISSUE THREAD

**Issue by GuangtaoLyu** [River-Zhang/SIFU#10]
![image](https://github.com/River-Zhang/SIFU/assets/57834464/bf352fe0-7996-4c00-9522-dd31dc0f82fd)

**Comment by GuangtaoLyu** [comment]
sorry. same to another issue.

**Comment by Zhangpei226** [comment]
I also have this question, and I would like to ask how you solved it?

**Comment by River-Zhang** [comment]
Probably you did not load the checkpoinit when running the script. It will run even if there is no ckpt. Please check if the ckpt is loaded correctly.
