### ISSUE TITLE
export_video is invalid?

### ISSUE THREAD

**Issue by GuangtaoLyu** [River-Zhang/SIFU#11]
![image](https://github.com/River-Zhang/SIFU/assets/57834464/b6b71aa7-462c-4f14-bc30-0009823aef25)

**Comment by River-Zhang** [comment]
Yes, I remove the export_video code so it's not available. However, you can follow ICON's code to export the video.

**Comment by GuangtaoLyu** [comment]
thank you



---Original---
From: "Zechuan ***@***.***&gt;
Date: Tue, Mar 12, 2024 16:02 PM
To: ***@***.***&gt;;
Cc: "Guangtao Lyu ( 吕光涛 ***@***.******@***.***&gt;;
Subject: Re: [River-Zhang/SIFU] export_video is invalid? (Issue #11)




 
Yes, I remove the export_video code so it's not available. However, you can follow ICON's code to export the video.
