### ISSUE TITLE
There is something wrong with the checkpoint downloading page.

### ISSUE THREAD

**Issue by Zejun-Yang** [River-Zhang/SIFU#12]
Excuse me, the checkpoint cannot be downloaded because of the webpage error. Please check it out if possible. Thank you!
<img width="761" alt="Snipaste_2024-03-18_15-30-54" src="https://github.com/River-Zhang/SIFU/assets/21038147/a27d18b5-e5a1-4d3e-b58d-dd5645e1218a">

**Comment by River-Zhang** [comment]
I'll check this. I'm trying to generate a permanent link but it may go wrong.

**Comment by River-Zhang** [comment]
https://1drv.ms/u/s!AtYZWFVkmRdwnEDF5XGtfLVzgLsH?e=44fqcD
You can use this link at the moment. But it is for temporary use.

**Comment by Zejun-Yang** [comment]
> https://1drv.ms/u/s!AtYZWFVkmRdwnEDF5XGtfLVzgLsH?e=44fqcD You can use this link at the moment. But it is for temporary use.

Thank you so much~

**Comment by River-Zhang** [comment]
I have updated a google drive link. I think it should be permanent.
