### ISSUE TITLE
The test result of my own model is inconsistent with the benchmark

### ISSUE THREAD

**Issue by glorioushonor** [River-Zhang/SIFU#14]
Thanks. The test results of the pre-trained model are exactly the same as yours. However, the results of my own training are very poor, and I don't know why. 
![image](https://github.com/River-Zhang/SIFU/assets/120625228/10b76fc4-1901-46d8-a377-9027bcb36e0a)
The test result is as follow.
![image](https://github.com/River-Zhang/SIFU/assets/120625228/c929f3ed-30a2-4fb2-9054-47c31c77c40e)

**Comment by River-Zhang** [comment]
That's strange. Maybe there is something wrong with the data processing. Currently, I haven't made a detailed training instruction. I'm reorganizing the codes of training and data processing because they are a bit messy. I'll update them as soon as possible.

**Comment by glorioushonor** [comment]
> That's strange. Maybe there is something wrong with the data processing. Currently, I haven't made a detailed training instruction. I'm reorganizing the codes of training and data processing because they are a bit messy. I'll update them as soon as possible.

Hello, have you finished reorganizing the codes for training and data processing? I'm still unable to reproduce the data from the paper.

**Comment by lywudi** [comment]
> Thanks. The test results of the pre-trained model are exactly the same as yours. However, the results of my own training are very poor, and I don't know why.谢谢.预训练模型的测试结果与您的测试结果完全相同。然而，我自己训练的结果很差，我不知道为什么。 ![image](https://private-user-images.githubusercontent.com/120625228/313662615-10b76fc4-1901-46d8-a377-9027bcb36e0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1ODQ1ODAsIm5iZiI6MTczNDU4NDI4MCwicGF0aCI6Ii8xMjA2MjUyMjgvMzEzNjYyNjE1LTEwYjc2ZmM0LTE5MDEtNDZkOC1hMzc3LTkwMjdiY2IzNmUwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwNDU4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjBjM2E3MDg2NTZmZTc2NzlmYTRmMWFjN2U3Nzk4MTAxN2U2YzU5YTNkNzkwZDBjZWUzMzQyNTM5ZmJiNDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1NJ1u2LA3ZxGuMz60RtGTM95MoewP4ccz-BPm5cqSi4) The test result is as follow. 测试结果如下。 ![image](https://private-user-images.githubusercontent.com/120625228/313661105-c929f3ed-30a2-4fb2-9054-47c31c77c40e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1ODQ1ODAsIm5iZiI6MTczNDU4NDI4MCwicGF0aCI6Ii8xMjA2MjUyMjgvMzEzNjYxMTA1LWM5MjlmM2VkLTMwYTItNGZiMi05MDU0LTQ3YzMxYzc3YzQwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwNDU4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWY4N2NiYzI5MDE0NTMyMmY1OTFhZDllODYwMDg5ZDk1NjQ1ZWYzODg5NmJlOTlkMTNkODA4ZjQyZDUxZDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PCFAP9TSuX9mKKaKK2x3aUyb962g7Dxeo8mGOJ2_gLA)

Hello, I've been having problems with the thuman dataset, can you please share the dataset and won't let you help in vain
