### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Zhangpei226** [River-Zhang/SIFU#16]
"Is it the case that the code specifies using GPU number 0, and if I want to use GPU number 1, does the command 'CUDA_VISIBLE_DEVICES=1 python -m apps.infer -cfg ./configs/sifu.yaml -gpu 0 -in_dir ./examples -out_dir ./results -loop_smpl 100 -loop_cloth 200 -hps_type pixie' have no effect, and manual modification of the code is required?"

**Comment by kinbac** [comment]
y can directly change the gpu number in codes, try it

**Comment by River-Zhang** [comment]
I think this command works. I tried on my device with this command 'CUDA_VISIBLE_DEVICES=1 python -m apps.infer -cfg ./configs/sifu.yaml -gpu 0 -in_dir ./examples -out_dir ./results -loop_smpl 100 -loop_cloth 200 -hps_type pixie', and it runs on GPU 1:
![image](https://github.com/River-Zhang/SIFU/assets/60051616/30b57d8f-0012-4fbd-893c-aef2674bc7dc)
