### ISSUE TITLE
The color of the inferred human body model

### ISSUE THREAD

**Issue by 12awei** [River-Zhang/SIFU#18]
![image](https://github.com/River-Zhang/SIFU/assets/95277262/2744eb0d-c65c-4dea-b703-20151d2338dc)
How to display the color of a 3D human model for inference?

**Comment by River-Zhang** [comment]
Currently, we haven't released the color refinement module. The model only supports the reconstruction of the geometry.

**Comment by kinbac** [comment]
> Currently, we haven't released the color refinement module. The model only supports the reconstruction of the geometry.

ok, thank you
