### ISSUE TITLE
Inference error, readme default param.

### ISSUE THREAD

**Issue by 1327476339** [River-Zhang/SIFU#2]
Body Fitting --- normal: 0.104 | silhouette: 0.054 | Total: **0.158**
d5acc65c50a71c7c54eb38323966f6c1_smpl.obj correct.

ICON infer error.
d5acc65c50a71c7c54eb38323966f6c1_recon.obj view：
![20240229-182731](https://github.com/River-Zhang/SIFU/assets/126777259/1725c97c-db24-44be-a026-c08e2dd04a58)

Cloth Refinement --- cloth:3.38728 | stiffness:0.66788 | rigid:0.04957 | laplacian:0.28668 | Total: **4.39141**

d5acc65c50a71c7c54eb38323966f6c1_cloth.gif view：
![d5acc65c50a71c7c54eb38323966f6c1_cloth](https://github.com/River-Zhang/SIFU/assets/126777259/86ddcd5d-6b68-4c08-b3a2-17d5ce3331e6)

thanks greate work!

**Comment by River-Zhang** [comment]
Thanks for trying our code and we will try to solve your concerns. It seems that the model predicts a totally wrong geometry. Could you please check if the checkpoint is correctly loaded? (because if it is not  loaded, the model still runs.)

**Comment by 1327476339** [comment]
Yes, sifu checkpoint was not loaded correctly. path error. thanks!
