### ISSUE TITLE
Regarding the issue during testing

### ISSUE THREAD

**Issue by glorioushonor** [River-Zhang/SIFU#21]
Hello, I would like to ask if it is not necessary to have the left and right normal maps of the SMPL model when testing with the CAPE dataset? I noticed that the dataset does not include them.

**Comment by River-Zhang** [comment]
Although it is not contained in the cape dataset, we render the left and right normal maps from the estimated SMPL-X during testing. You can check the code in test_step().
![image](https://github.com/River-Zhang/SIFU/assets/60051616/12fdd376-ec67-4aaf-b300-70d5942d2b9e)
