### ISSUE TITLE
THuman2.0 test list

### ISSUE THREAD

**Issue by jinnan-chen** [River-Zhang/SIFU#22]
Hi thanks for great work!
Is it possible to provide THuman2.0 test list? Thanks!

**Comment by River-Zhang** [comment]
Sorry about the late reply. We use the scans from 0505-0525 for testing.

**Comment by jinnan-chen** [comment]
What about the test views of these meshes for the texture rendering camparison?

**Comment by River-Zhang** [comment]
We render four views of each mesh, 0, 90, 180, 270 for testing.

**Comment by River-Zhang** [comment]
To be more clear, we input the front side image of the scans, and render the four views to calculate PSNR.

**Comment by jinnan-chen** [comment]
Noted with thanks!
