### ISSUE TITLE
Processing for THuman2.0

### ISSUE THREAD

**Issue by glorioushonor** [River-Zhang/SIFU#24]
Hello, you mentioned optimizing the rendering process for THuman2.0 in your work on GTA. [Question about numbers, evaluation. #9](https://github.com/River-Zhang/GTA/issues/9#issuecomment-1972339061) Could you provide details on this? Or is it that your modified dataset processing script has been made publicly available in the code repository? Do I need to use my script to reprocess the THuman2.0 dataset? Because previously, when I tried to reproduce your code using ICON's data, I couldn't achieve experimental results consistent with those in the paper.

**Comment by River-Zhang** [comment]
The difference in data processing between ours and GTA is that we render the left and right view normals of SMPL-X. This part could be found in scripts/render_single.py, lines 306-353.

**Comment by glorioushonor** [comment]
> The difference in data processing between ours and GTA is that we render the left and right view normals of SMPL-X. This part could be found in scripts/render_single.py, lines 306-353.

Thank you for your response, but you didn't address my point. You mentioned in GTA, "While training and testing SIFU model with THuman2.0, we find that **some of the SMPL-X model in the dataset has wrong scales that can not fit the scan**. This error might have been introduced during the dataset processing stage. So we reprocess the SMPL-X scans to make it right." **Could you provide the SMPL-X scans after your optimization?**

**Comment by River-Zhang** [comment]
We didn't optimize the SMPL-X scans ourselves but redownload the SMPL-X fits of THuman2.0 and this solves the problem.

**Comment by glorioushonor** [comment]
> We didn't optimize the SMPL-X scans ourselves but redownload the SMPL-X fits of THuman2.0 and this solves the problem.

Is this the document? So I need to reapply for the Thuman 2.0 dataset to update the SMPL-X fits?
![image](https://github.com/River-Zhang/SIFU/assets/120625228/de00e581-32b7-4bef-b769-4ee248b04ed3)

**Comment by River-Zhang** [comment]
If yours are recently downloaded, I don't think you need to update. We did this because we accidentally change the SMPL-X files during reading the data.

**Comment by glorioushonor** [comment]
> If yours are recently downloaded, I don't think you need to update. We did this because we accidentally change the SMPL-X files during reading the data.

I'd like to give it a try because I haven't been able to reproduce the numbers in the paper so far. [The test result of my own model is inconsistent with the benchmark #14](https://github.com/River-Zhang/SIFU/issues/14#issue-2191967536) Besides this issue, I can't think of any other problems. My dataset was downloaded a year ago. So, should I redownload the THuman2.0 SMPLX files and then re-render the normal maps for SMPL in all four directions?

**Comment by River-Zhang** [comment]
Yes, you can try that.

**Comment by glorioushonor** [comment]
> Yes, you can try that.

Perhaps I should first test your model on Thuman 2.0? If there are issues, it should be related to the data, right? Could you provide the code or instructions for testing on Thuman 2.0?

**Comment by glorioushonor** [comment]
> Yes, you can try that.

I tested using my current THuman2.0 dataset, and it seems to be significantly worse than the data in the paper.
![image](https://github.com/River-Zhang/SIFU/assets/120625228/cf0e1003-9c6b-4fe3-943a-e51c62ccaaf9)
![image](https://github.com/River-Zhang/SIFU/assets/120625228/302439d2-e82b-401c-90af-2ffd111a5ed2)

**Comment by River-Zhang** [comment]
I think this might be caused by two reasons:
1. We test on THuman2.0 similar to CAPE, the input image is rendered around the scan with 0,120,240 angles.
![image](https://github.com/River-Zhang/SIFU/assets/60051616/5eb20ce1-77e8-47d9-b747-97dd8779376d)
2. We directly use the SMPL-X normals from our preprocessed dataset (which are rendered by opengl). The normals have been loaded in in_tensor. Therefore it does not fit the following condition
![image](https://github.com/River-Zhang/SIFU/assets/60051616/723b0470-cca4-4e92-af74-5329fe0456a3)
However, if you don't have the SMPL-X normals, it will use pytorch3D renderer to render the side normals (we apply this on CAPE). We notice that these two renderers are a little different and the testing results could be better when using opengl, as we trained the model with the side normals rendered by opengl.

**Comment by glorioushonor** [comment]
> I think this might be caused by two reasons:
> 
> 1. We test on THuman2.0 similar to CAPE, the input image is rendered around the scan with 0,120,240 angles.
>    ![image](https://private-user-images.githubusercontent.com/60051616/328913745-5eb20ce1-77e8-47d9-b747-97dd8779376d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzgxNTksIm5iZiI6MTcxNTE3Nzg1OSwicGF0aCI6Ii82MDA1MTYxNi8zMjg5MTM3NDUtNWViMjBjZTEtNzdlOC00N2Q5LWI3NDctOTdkZDg3NzkzNzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0MTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjRhMmFkYmFlYTI0M2MzNWUxZDI5MDJjYzMwODg0OWJiNjYxMzRkODdhZWRmOWE5Mjc0MmE2OGY3ZDFiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vaATfGML9vRjm31VXTX4YTwLwtk0mTsl7MZm7YC2cLo)
> 2. We directly use the SMPL-X normals from our preprocessed dataset (which are rendered by opengl). The normals have been loaded in in_tensor. Therefore it does not fit the following condition
>    ![image](https://private-user-images.githubusercontent.com/60051616/328915843-723b0470-cca4-4e92-af74-5329fe0456a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzgxNTksIm5iZiI6MTcxNTE3Nzg1OSwicGF0aCI6Ii82MDA1MTYxNi8zMjg5MTU4NDMtNzIzYjA0NzAtY2NhNC00ZTkyLWFmNzQtNTMyOWZlMDQ1NmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0MTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZTQ0NzliNTk4NGViMGQyZGEzYzkxOTg1NGY5MTk4OWM1N2Y1ZDYxMjQzYjBlMmY3ZTA0Y2Q4ZjU2NDM2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1uevqHe_Yxzfhq5gyejKRM-keFGRNI_vujVdsHQhCYY)
>    However, if you don't have the SMPL-X normals, it will use pytorch3D renderer to render the side normals (we apply this on CAPE). We notice that these two renderers are a little different and the testing results could be better when using opengl, as we trained the model with the side normals rendered by opengl.

1. Got it, I'll retest it then. So, it seems you might have responded incorrectly to this[ issue](https://github.com/River-Zhang/SIFU/issues/22#issuecomment-2099831663)?
2. I might have used the dataset rendered with OpenGL. Because I rendered the side view of the SMPL model according to your script. Moreover, I added markers in this section, and there was no output of "*".
![image](https://github.com/River-Zhang/SIFU/assets/120625228/a9953bb3-3564-40d9-a045-68a170021e2e)
![image](https://github.com/River-Zhang/SIFU/assets/120625228/2a543f34-8809-45e8-b4eb-cd877ba8a0d4)
![image](https://github.com/River-Zhang/SIFU/assets/120625228/b8a1d392-2c19-463e-84fd-506e786f8435)
3.When I re-downloaded the SMPL-X fits of THuman2.0, should I use the `"wget https://download.is.tue.mpg.de/icon/SMPL-X.zip --no-check-certificate -O ./data/thuman2/SMPL-X.zip"`  from ICON, or the link within [THuman2.0](https://github.com/ytrock/THuman2.0-Dataset)? I initially used the data from ICON, and I found that the SMPL-X fits from ICON haven't been updated.

**Comment by River-Zhang** [comment]
There might be a misunderstanding. I mean for each input image, we render four views 0,90,180,270 to calculate PSNR, SSIM, LPIPS.etc. I'll illustrate that more clearly.

**Comment by glorioushonor** [comment]
> There might be a misunderstanding. I mean for each input image, we render four views 0,90,180,270 to calculate PSNR, SSIM, LPIPS.etc. I'll illustrate that more clearly.

For my questions 2 and 3, do you have any better suggestions? I've been stuck on this for a long time. 😢

**Comment by River-Zhang** [comment]
I retest the model on THuman2.0 and the results are 
![image](https://github.com/River-Zhang/SIFU/assets/60051616/2dc8f8ba-fcb4-45e5-869b-7da87eba26e0)
I'm not sure what caused this, but we plan to release the data processing code before 6.17.

And for SMPLX, we download from https://github.com/ytrock/THuman2.0-Dataset.

**Comment by glorioushonor** [comment]
> I retest the model on THuman2.0 and the results are ![image](https://private-user-images.githubusercontent.com/60051616/328941195-2dc8f8ba-fcb4-45e5-869b-7da87eba26e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODE0MzIsIm5iZiI6MTcxNTE4MTEzMiwicGF0aCI6Ii82MDA1MTYxNi8zMjg5NDExOTUtMmRjOGY4YmEtZmNiNC00NWU1LTg2OWItN2RhODdlYmEyNmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1MTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NDZhYmY3MjlmY2Q3Y2UxYWQ4ZGU0NzgxNTZhN2UzOWI4ZTE3MjhjOGQ2NzUxNGNkNzU3OWY3ZmMwYTk4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okb7VdAxWrEO4gvSlXnD-F__zHdhbReI7gEZ1XspNk4) I'm not sure what caused this, but we plan to release the data processing code before 6.17.
> 
> And for SMPLX, we download from https://github.com/ytrock/THuman2.0-Dataset.

Thanks. The only reason I can think of is the preprocessing of the dataset. I noticed that there are indeed differences between the SMPL-fits provided by ICON and THuman2.0. So I need to download the SMPL-fits from THuman2.0 and rename them to match the original naming convention. However, I didn't anticipate that the differences in SMPL-fits would lead to such a significant drop in performance, as my own training results were also very poor. But wasn't SIFU claimed to be better at handling perturbations in the SMPL model?

**Comment by glorioushonor** [comment]
> I retest the model on THuman2.0 and the results are ![image](https://private-user-images.githubusercontent.com/60051616/328941195-2dc8f8ba-fcb4-45e5-869b-7da87eba26e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzI3ODMsIm5iZiI6MTcxNTI3MjQ4MywicGF0aCI6Ii82MDA1MTYxNi8zMjg5NDExOTUtMmRjOGY4YmEtZmNiNC00NWU1LTg2OWItN2RhODdlYmEyNmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE2MzQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MGIwM2ZhYjg3MzUxNTc0MmRkYjU5OTZmMmViNjk5MjY2MzAxZDY5ZTMxM2M4MGRmNWJjOWVkNzM0ZjJmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MnUTbZGkhaGJy2q1ixeM7aSwrnt1Ap_QT9Z68HcPZP0) I'm not sure what caused this, but we plan to release the data processing code before 6.17.
> 
> And for SMPLX, we download from https://github.com/ytrock/THuman2.0-Dataset.

After update the SMPL-fits, did you recompute the visibility? I saw you use `'vis_path': osp.join(self.root, **old_folder**, 'vis', f'{rotation:03d}.pt')`. It seems that you used the ICON's visibility.

**Comment by jingi0614** [comment]
I’m experiencing the same issue. Has it been resolved?
If it has been resolved, could you help me with it?

**Comment by lywudi** [comment]
> Hello, you mentioned optimizing the rendering process for THuman2.0 in your work on GTA. [Question about numbers, evaluation. #9](https://github.com/River-Zhang/GTA/issues/9#issuecomment-1972339061) Could you provide details on this? Or is it that your modified dataset processing script has been made publicly available in the code repository? Do I need to use my script to reprocess the THuman2.0 dataset? Because previously, when I tried to reproduce your code using ICON's data, I couldn't achieve experimental results consistent with those in the paper.你好，你提到在你的工作中优化渲染过程的THUMAN2.0的GTA。[关于数字的问题，评估。#9](https://github.com/River-Zhang/GTA/issues/9#issuecomment-1972339061)你能提供一些细节吗？或者是你修改过的数据集处理脚本已经在代码库中公开了？我是否需要使用我的脚本重新处理THuman2.0数据集？因为之前，当我试图使用ICON的数据复制您的代码时，我无法获得与论文中一致的实验结果。

How do you process thre thuman2.0?Could you share the instructions?
