### ISSUE TITLE
Wrong body generation

### ISSUE THREAD

**Issue by Crazywangq** [River-Zhang/SIFU#28]
Hello, thank you for providing the open-source code. Recently, when I attempted to replicate it, I encountered an issue where the SMPL human body was generated correctly, but the clothed human body appeared as a square erroneously.
![微信图片_20240517093438](https://github.com/River-Zhang/SIFU/assets/129187354/65c5b70d-fa34-4abb-9003-514a48092b0b)
![微信图片_20240517093500](https://github.com/River-Zhang/SIFU/assets/129187354/3e8e74ed-137f-4d40-8694-432efefa9019)
![微信图片_20240517093515](https://github.com/River-Zhang/SIFU/assets/129187354/f13461e6-2e07-48d2-9659-57328c2e098e)
My running code is as follows
![微信图片_20240517093626](https://github.com/River-Zhang/SIFU/assets/129187354/1264bff0-8c10-4b3c-aef1-632ef7cce5ba)
Has anyone encountered similar issues? Is it due to the files I downloaded or some other reason? Could someone assist me? Thank you very much.

**Comment by River-Zhang** [comment]
It seems that the sifu.ckpt is not loaded. Please check if the ckpt path is correct (if the path was wrong, the model still runs).

**Comment by Crazywangq** [comment]
> It seems that the sifu.ckpt is not loaded. Please check if the ckpt path is correct (if the path was wrong, the model still runs).

Thank you very much for your response. The issue has been resolved, and now I can generate a complete dressed human figure.
I have another question I'd like to ask. The human figure generated by the sifu model does not include texture information. Previously, I replicated your GTA model, and the final result included textures directly. Is it the case that the sifu model only provides a mesh model of the dressed human figure, and that additional methods are required to restore texture and color information?
Looking forward to your reply.

**Comment by Crazywangq** [comment]
Oh, I see how to do it now. Thank you!

> > It seems that the sifu.ckpt is not loaded. Please check if the ckpt path is correct (if the path was wrong, the model still runs).
> 
> Thank you very much for your response. The issue has been resolved, and now I can generate a complete dressed human figure. I have another question I'd like to ask. The human figure generated by the sifu model does not include texture information. Previously, I replicated your GTA model, and the final result included textures directly. Is it the case that the sifu model only provides a mesh model of the dressed human figure, and that additional methods are required to restore texture and color information? Looking forward to your reply.
