### ISSUE TITLE
There's no cloth on the refine.obj

### ISSUE THREAD

**Issue by JohnCachy** [River-Zhang/SIFU#34]
Hi!
Thanks  for your great work!
I ran the comand:

python -m apps.infer -cfg ./configs/sifu.yaml -gpu 0 -in_dir ./examples -out_dir ./results -loop_smpl 100 -loop_cloth 200 -hps_type pixie
Then i got 7 obj files.But there's no cloth on all of them.
How can I get obj files with clothes? Did I miss any file uesd to refine?
<img width="776" alt="image" src="https://github.com/user-attachments/assets/26c2e339-b221-4fc6-a4c6-9693dc0c75f8">

refine.obj:
<img width="659" alt="image" src="https://github.com/user-attachments/assets/2a340709-fc65-4c5a-9bf6-853f8d448f99">

**Comment by wyiguanw** [comment]
I met same issue, have you solve it

**Comment by River-Zhang** [comment]
Are you saying that the mesh color is not being displayed? Since we haven’t released the code for texture reconstruction yet, the current version of the code can only produce results without textures.
