### ISSUE TITLE
missing smplx_vertex_lmkid.npy

### ISSUE THREAD

**Issue by sdy-ny** [River-Zhang/SIFU#4]
Hi, thank you for releasing the code. I tried the demo code but got this error.

FileNotFoundError: [Errno 2] No such file or directory: './data/smpl_related/smpl_data/smplx_vertex_lmkid.npy'

Could you please share this file?

Thanks!

**Comment by GuangtaoLyu** [comment]
+1

**Comment by River-Zhang** [comment]
Let me check this. Here is a link to this file on onedrive: https://1drv.ms/u/s!AtYZWFVkmRdwnEGztvH42Pmd4dYK?e=Ql1hsq
I'll check what is wrong with the data downloading instructions and update it as soon as possible. Thanks for pointing out!

**Comment by GuangtaoLyu** [comment]
thank you. i will try it.



---Original---
From: "Zechuan ***@***.***&gt;
Date: Wed, Mar 6, 2024 19:04 PM
To: ***@***.***&gt;;
Cc: "Guangtao Lyu ( 吕光涛 ***@***.******@***.***&gt;;
Subject: Re: [River-Zhang/SIFU] missing smplx_vertex_lmkid.npy (Issue #4)




 
Let me check this. Here is a link to this file on onedrive: https://1drv.ms/u/s!AtYZWFVkmRdwnEGztvH42Pmd4dYK?e=Ql1hsq
 I'll check what is wrong with the data downloading instructions and update it as soon as possible. Thanks for pointing out!

**Comment by GuangtaoLyu** [comment]
missing  MANO_SMPLX_vertex_ids.pkl

**Comment by GuangtaoLyu** [comment]
https://huggingface.co/lilpotat/pytorch3d/tree/main/smpl_data 
this link has many related files?

**Comment by Zhangpei226** [comment]
The website is not accessible. Could you please share the source file with me instead?

**Comment by Zhangpei226** [comment]
> https://huggingface.co/lilpotat/pytorch3d/tree/main/smpl_data this link has many related files?

The website is not accessible. Could you please share the source file with me instead?

**Comment by River-Zhang** [comment]
This website is accessible but you may need a VPN or tizi to open it.

**Comment by Zhangpei226** [comment]
Thanks，I got it.
