### ISSUE TITLE
The test results of the pre-trained model are inconsistent with the benchmark

### ISSUE THREAD

**Issue by glorioushonor** [River-Zhang/SIFU#7]
Hello, I have successfully tested the pre-trained model, but I found that the results do not match the data in the benchmark, especially for CAPE-NFP. Is this normal? Looking forward to your reply.
![image](https://github.com/River-Zhang/SIFU/assets/120625228/0f51fbbe-d879-4c45-97f3-dd08515790cc)

**Comment by River-Zhang** [comment]
It seems that you're using the whole cape dataset (containing 150 scans) rather than cape-NFP (containing 100 scans). Besides we did not refer to cape-easy or cape-hard. We just sum the results and calculate the average. 
![image](https://github.com/River-Zhang/SIFU/assets/60051616/d2332f64-456c-4c8d-9b70-b61ebeb08c96)
Here is the testing result for the whole cape dataset.  You can test again on CAPE-NFP (I guess it's in pose.txt?)

**Comment by glorioushonor** [comment]
> It seems that you're using the whole cape dataset (containing 150 scans) rather than cape-NFP (containing 100 scans). Besides we did not refer to cape-easy or cape-hard. We just sum the results and calculate the average. ![image](https://private-user-images.githubusercontent.com/60051616/309563957-d2332f64-456c-4c8d-9b70-b61ebeb08c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODQzNDQsIm5iZiI6MTcwOTQ4NDA0NCwicGF0aCI6Ii82MDA1MTYxNi8zMDk1NjM5NTctZDIzMzJmNjQtNDU2Yy00YzhkLTliNzAtYjYxZWJlYjA4Yzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE2NDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNDY5ZWMyMzBhNmM2Y2JjN2Y0OTMwMWNkMmU2MjE0MWQ4ZTIwMDY3NGE3OTM1M2FhZWQxMjUxNTc5NTg4MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.27poSFTqPApkyFZmQi_oe7RD1bSXLrK9c1pbToR0HCg) Here is the testing result for the whole cape dataset. You can test again on CAPE-NFP (I guess it's in pose.txt?)

In my opinion, the contents of pose.txt are consistent with the last 100 data entries in all.txt. The first fifty entries in all.txt are cape-easy, which is essentially CAPE-FP; the last one hundred entries in all.txt are cape-hard, which is essentially CAPE-NFP.
```
accu_outputs = accumulate(
            outputs,
            rot_num=3,
            split={
                "cape-easy": (0, 50),
                "cape-hard": (50, 150)
            },
        )
```

**Comment by River-Zhang** [comment]
Let me check out this

**Comment by River-Zhang** [comment]
I tested on CAPE-NFP solely and the result is 
![image](https://github.com/River-Zhang/SIFU/assets/60051616/d5865353-96c5-432a-82c8-2543d2e085cb)
and the whole cape dataset
![image](https://github.com/River-Zhang/SIFU/assets/60051616/6fe59a33-93e2-4ad8-8baa-9ba8c8bf46a1)

It seems that I might have released an old version ckpt. I'll change to the correct one as soon as possible.

**Comment by River-Zhang** [comment]
I have updated the ckpt (https://1drv.ms/u/s!AtYZWFVkmRdwnEDF5XGtfLVzgLsH?e=bpgsji). You can test this again. Thanks very much!

**Comment by glorioushonor** [comment]
> I have updated the ckpt (https://1drv.ms/u/s!AtYZWFVkmRdwnEDF5XGtfLVzgLsH?e=bpgsji). You can test this again. Thanks very much!

@River-Zhang  Thanks. The test results of the pre-trained model are exactly the same as yours. However, the results of my own training are very poor, and I don't know why. Was your pre-trained model only trained for 10 epochs?
![image](https://github.com/River-Zhang/SIFU/assets/120625228/3dc49536-daf6-4c8b-97c6-2683377d0496)

**Comment by River-Zhang** [comment]
Yes, it is trained only 10 epochs.
