### ISSUE TITLE
The link is dead.  https://www.dropbox.com/s/aeulffqzb3zmh8x/pare-github-data.zip

### ISSUE THREAD

**Issue by GuangtaoLyu** [River-Zhang/SIFU#9]
![image](https://github.com/River-Zhang/SIFU/assets/57834464/3aec89f9-ed14-4969-87bb-748a816f66c7)
https://www.dropbox.com/s/aeulffqzb3zmh8x/pare-github-data.zip

**Comment by River-Zhang** [comment]
Pare is not used in our model. You can ignore this. I'll update the data downloading file. Thanks very much!

**Comment by GuangtaoLyu** [comment]
OK. thank you.



---Original---
From: "Zechuan ***@***.***&gt;
Date: Wed, Mar 6, 2024 19:07 PM
To: ***@***.***&gt;;
Cc: "Guangtao Lyu ( 吕光涛 ***@***.******@***.***&gt;;
Subject: Re: [River-Zhang/SIFU] The link is dead. https://www.dropbox.com/s/aeulffqzb3zmh8x/pare-github-data.zip (Issue #9)




 
Pare is not used in our model. You can ignore this. I'll update the data downloading file. Thanks very much!
